# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ssl_requirement"
  s.version = "1.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["RailsJedi", "David Heinemeier Hansson", "jcnetdev", "bcurren", "bmpercy", "revo", "nathany"]
  s.date = "2014-06-17"
  s.description = "SSL requirement adds a declarative way of specifying that certain actions should only be allowed to run under SSL, and if they're accessed without it, they should be redirected."
  s.email = "nathan@yardsticksoftware.com"
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README",
    "Rakefile",
    "VERSION",
    "init.rb",
    "lib/ssl_requirement.rb",
    "lib/url_rewriter.rb",
    "rails/init.rb",
    "shoulda_macros/ssl_requirement_macros.rb",
    "ssl_requirement.gemspec",
    "test/ssl_requirement_test.rb",
    "test/url_rewriter_test.rb"
  ]
  s.homepage = "http://github.com/yardstick/ssl_requirement"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Allow controller actions to force SSL on specific parts of the site."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

